version: '3.8'
services:
  app:
    build:
      context: ./app
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    environment:
      - SOCKET_SERVER_HOST=${SOCKET_SERVER_HOST:-socket_server}
      - SOCKET_SERVER_PORT=${SOCKET_SERVER_PORT:-5000}
    depends_on:
      - mongodb
      - socket_server

  socket_server:
    build:
      context: ./app
    command: python socket_server.py
    ports:
      - "${SOCKET_SERVER_PORT:-5000}:${SOCKET_SERVER_PORT:-5000}"
    environment:
      - MONGO_HOST=${MONGO_HOST:-mongodb}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - DB_NAME=${DB_NAME:-message_db}
      - COLLECTION_NAME=${COLLECTION_NAME:-messages}

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: